#
# Whenever version.php is changed, add the latest version
# to the Moodle Plugins directory at https://moodle.org/plugins
#
name: MOODLE_310_STABLE - Releasing in the Plugins directory

on:
  push:
    branches:
      - MOODLE_310_STABLE
    paths:
      - 'version.php'

jobs:
  workflow_group_310_plus_release:
    uses: catalyst/catalyst-moodle-workflows/.github/workflows/moodle-311-release.yml@main
    with:
      plugin_name: search_elastic
      extra_plugin_runners: 'moodle-plugin-ci add-plugin catalyst/moodle-local_aws'
      disable_grunt: true
    secrets:
      moodle_org_token: ${{ secrets.MOODLE_ORG_TOKEN }}
